name: Build and Deploy Maven Project

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"

      - name: Setup GPG
        run: |
          echo "$GPG_PRIVATE_KEY" | gpg --batch --import
          gpg --no-tty --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys $(gpg --list-secret-keys --keyid-format LONG | grep 'sec' | awk '{print $2}' | cut -d'/' -f2)
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Create .maven/settings.xml
        run: |
          mkdir -p .maven
          echo "<settings>
                  <servers>
                    <server>
                      <id>central</id>
                      <username>$SONATYPE_USERNAME</username>
                      <password>$SONATYPE_PASSWORD</password>
                      <passphrase>$GPG_PASSPHRASE</passphrase>
                    </server>
                  </servers>
                  <profiles>
                    <profile>
                      <id>central</id>
                      <activation>
                        <activeByDefault>true</activeByDefault>
                      </activation>
                      <properties>
                        <gpg.executable>gpg</gpg.executable>
                      </properties>
                    </profile>
                  </profiles>
                </settings>" > .maven/settings.xml
        env:
          SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
          SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
          GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Sonatype
        run: mvn clean deploy --settings .maven/settings.xml
