name: Build and Deploy Maven Project

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '8'

    - name: Create .maven/settings.xml
      run: |
        mkdir -p .maven
        echo "<settings>
                <servers>
                  <server>
                    <id>ossrh</id>
                    <username>${{ secrets.SONATYPE_USERNAME }}</username>
                    <password>${{ secrets.SONATYPE_PASSWORD }}</password>
                  </server>
                </servers>
              </settings>" > .maven/settings.xml

    - name: Build with Maven
      run: mvn clean install

    - name: Deploy to Sonatype
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: mvn deploy -DskipTests --settings .maven/settings.xml
